import { Category } from './interfaces/Category';

export const defects: Category[] = [
  {
    _id: 1,
    name: 'Abrasion / Cover wear',
    defects: [
      {
        name: 'Glossy, smooth; no abrasion',
        checked: false,
        value: 100,
        image: 'assets/images/perfect_in_every_way.jpg',
      },
      {
        name: 'Just noticeable abrasion',
        checked: false,
        value: 94,
        image: 'assets/images/abrasion/94.jpg',
      },
      {
        name: 'Small Area of Scuffing',
        checked: false,
        value: 75,
        image: 'assets/images/abrasion/75.jpg',
      },
      {
        name: 'Colour Breaking Abrasions',
        checked: false,
        value: 70,
        image: 'assets/images/abrasion/70.jpg',
      },
      {
        name: 'Large Areas of Visible Abrasion',
        checked: false,
        value: 65,
        image: 'assets/images/abrasion/65.jpg',
      },
      {
        name: 'Deep Abrasions/Spine Wear',
        checked: false,
        value: 50,
        image: 'assets/images/abrasion/50.jpg',
      },
    ],
  },
  {
    _id: 2,
    name: 'Centration / Miswrap',
    defects: [
      {
        name: 'Perfect Centration',
        checked: false,
        value: 100,
        image: 'assets/images/perfect_in_every_way.jpg',
      },
      {
        name: 'Off centre 1-3mm',
        checked: false,
        value: 99,
        image: 'assets/images/centration/99.jpg',
      },
      {
        name: 'Noticeable miswrap',
        checked: false,
        value: 96,
        image: 'assets/images/centration/96.jpg',
      },
      {
        name: 'Severe miswrap',
        checked: false,
        value: 90,
        image: 'assets/images/centration/90.jpg',
      },
      {
        name: 'Wild miswrap',
        checked: false,
        value: 85,
        image: 'assets/images/centration/85.jpg',
      },
    ],
  },
  {
    _id: 3,
    name: 'Colour lift',
    defects: [
      {
        name: 'None- Flat & Smooth',
        checked: false,
        value: 100,
        image: 'assets/images/perfect_in_every_way.jpg',
      },
      {
        name: '3mm area removed',
        checked: false,
        value: 70,
        image: 'assets/images/colourlift/70.jpg',
      },
      {
        name: '3-10 mm area removed',
        checked: false,
        value: 65,
        image: 'assets/images/colourlift/65.jpg',
      },
      {
        name: '10-20 mm Patch Removed',
        checked: false,
        value: 40,
        image: 'assets/images/colourlift/40.jpg',
      },
      {
        name: '> 10mm Patch Removed',
        checked: false,
        value: 30,
        image: 'assets/images/colourlift/30.jpg',
      },
    ],
  },
  {
    _id: 4,
    name: 'Colour spots',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/perfect_in_every_way.jpg',
      },
      {
        name: 'Tiny flecks',
        checked: false,
        value: 99,
        image: 'assets/images/colourspots/99.jpg',
      },
      {
        name: 'Several Flecks/large donuts',
        checked: false,
        value: 96,
        image: 'assets/images/colourspots/96.jpg',
      },
    ],
  },
  {
    _id: 5,
    name: 'Corner creases',
    defects: [
      {
        name: 'Sharp Corners',
        checked: false,
        value: 100,
        image: 'assets/images/cornerrounding/100.jpg',
      },
      {
        name: 'Just Noticeable',
        checked: false,
        value: 99,
        image: 'assets/images/cornercreases/99.jpg',
      },
      {
        name: 'Blunting',
        checked: false,
        value: 96,
        image: 'assets/images/cornercreases/96.jpg',
      },
      {
        name: '5mm Crease',
        checked: false,
        value: 92,
        image: 'assets/images/cornercreases/92.jpg',
      },
      {
        name: 'Several Minor Creases',
        checked: false,
        value: 85,
        image: 'assets/images/cornercreases/85.jpg',
      },
      {
        name: 'Multiple Light Creases',
        checked: false,
        value: 75,
        image: 'assets/images/cornercreases/75.jpg',
      },
      {
        name: 'Small General Atritions',
        checked: false,
        value: 70,
        image: 'assets/images/cornercreases/70.jpg',
      },
      {
        name: '40 mm Colour Breaking Creases',
        checked: false,
        value: 65,
        image: 'assets/images/cornercreases/65.jpg',
      },
      {
        name: 'Large Corner Crease',
        checked: false,
        value: 40,
        image: 'assets/images/cornercreases/40.jpg',
      },
      {
        name: 'Corner Attrition',
        checked: false,
        value: 20,
        image: 'assets/images/cornercreases/20.jpg',
      },
    ],
  },
  {
    _id: 6,
    name: 'Corner rounding',
    defects: [
      {
        name: 'Sharp Corner',
        checked: false,
        value: 100,
        image: 'assets/images/cornerrounding/100.jpg',
      },
      {
        name: 'Just Perceptibly blunted',
        checked: false,
        value: 99,
        image: 'assets/images/cornerrounding/99.jpg',
      },
      {
        name: 'Blunted',
        checked: false,
        value: 96,
        image: 'assets/images/cornerrounding/96.jpg',
      },
      {
        name: 'Fibres Showing',
        checked: false,
        value: 90,
        image: 'assets/images/cornerrounding/90.jpg',
      },
      {
        name: 'Deformation with Colour Breaks',
        checked: false,
        value: 85,
        image: 'assets/images/cornerrounding/85.jpg',
      },
      {
        name: 'Rounded; radius < 3mm',
        checked: false,
        value: 70,
        image: 'assets/images/cornerrounding/70.jpg',
      },
      {
        name: 'Rounded; Radius > 3mm',
        checked: false,
        value: 65,
        image: 'assets/images/cornerrounding/65.jpg',
      },
      {
        name: 'No Corner',
        checked: false,
        value: 20,
        image: 'assets/images/cornerrounding/20.jpg',
      },
    ],
  },
  {
    _id: 7,
    name: 'Cover gloss',
    defects: [
      {
        name: 'As New',
        checked: false,
        value: 100,
        image: 'assets/images/covergloss/100.jpg',
      },
      {
        name: 'High Gloss',
        checked: false,
        value: 96,
        image: 'assets/images/covergloss/96.jpg',
      },
      {
        name: 'Moderate Gloss Remaining',
        checked: false,
        value: 90,
        image: 'assets/images/covergloss/90.jpg',
      },
      {
        name: 'Dull',
        checked: false,
        value: 80,
        image: 'assets/images/covergloss/80.jpg',
      },
      {
        name: 'Matt',
        checked: false,
        value: 60,
        image: 'assets/images/covergloss/60.jpg',
      },
    ],
  },
  {
    _id: 8,
    name: 'Cover page missing',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/coverpagemissing/100.jpg',
      },
      {
        name: 'Back Cover Missing- Front Taped On',
        checked: false,
        value: 10,
        image: 'assets/images/coverpagemissing/10.jpg',
      },
      {
        name: 'Entire Cover Missing',
        checked: false,
        value: 1,
        image: 'assets/images/coverpagemissing/01.jpg',
      },
    ],
  },
  {
    _id: 9,
    name: 'Cover whiteness',
    defects: [
      {
        name: 'White',
        checked: false,
        value: 100,
        image: 'assets/images/coverwhiteness/100.jpg',
      },
      {
        name: 'Off-White/White',
        checked: false,
        value: 99,
        image: 'assets/images/coverwhiteness/99.jpg',
      },
      {
        name: 'Off-White',
        checked: false,
        value: 96,
        image: 'assets/images/coverwhiteness/96.jpg',
      },
      {
        name: 'Cream/Off-white',
        checked: false,
        value: 94,
        image: 'assets/images/coverwhiteness/94.jpg',
      },
      {
        name: 'Cream',
        checked: false,
        value: 90,
        image: 'assets/images/coverwhiteness/90.jpg',
      },
      {
        name: 'Tan',
        checked: false,
        value: 50,
        image: 'assets/images/coverwhiteness/80.jpg',
      },
      {
        name: 'Brown',
        checked: false,
        value: 30,
        image: 'assets/images/coverwhiteness/15.jpg',
      },
    ],
  },
  {
    _id: 10,
    name: 'Cutouts (Interior/Exterior)',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/cutouts/100.jpg',
      },
      {
        name: '5mm sq. Piece out',
        checked: false,
        value: 75,
        image: 'assets/images/pieceout/80.jpg',
      },
      {
        name: '20mm Piece out of Cover',
        checked: false,
        value: 40,
        image: 'assets/images/cutouts/15.jpg',
      },
      {
        name: 'Coupon Cut; Non-Story Page',
        checked: false,
        value: 30,
        image: 'assets/images/couponcut/30.jpg',
      },
      {
        name: 'Coupon Cut- Story Page',
        checked: false,
        value: 25,
        image: 'assets/images/couponcut/20.jpg',
      },
      {
        name: 'Large Piece/Coupon Out of Cover',
        checked: false,
        value: 5,
        image: 'assets/images/cutouts/05.jpg',
      },
    ],
  },
  {
    _id: 11,
    name: 'Digs & Gouges',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/spinecreases/100.jpg',
      },
      {
        name: '2mm Non-Colour Breaking',
        checked: false,
        value: 94,
        image: 'assets/images/digsgouges/94.jpg',
      },
      {
        name: 'Long Non-Color Breaking',
        checked: false,
        value: 90,
        image: 'assets/images/digsgouges/90.jpg',
      },
      {
        name: '5mm Dent/Bale Marks',
        checked: false,
        value: 75,
        image: 'assets/images/digsgouges/75.jpg',
      },
      {
        name: 'Page thickness Gouge',
        checked: false,
        value: 30,
        image: 'assets/images/digsgouges/30.jpg',
      },
      {
        name: 'Long Drag Marks',
        checked: false,
        value: 25,
        image: 'assets/images/digsgouges/25.jpg',
      },
      {
        name: 'Pieces out from Several Pages',
        checked: false,
        value: 20,
        image: 'assets/images/digsgouges/20.jpg',
      },
    ],
  },
  {
    _id: 12,
    name: 'Edge wear and Chipping',
    defects: [
      {
        name: 'Sharp, straight edge',
        checked: false,
        value: 100,
        image: 'assets/images/edgewearchipping/100.jpg',
      },
      {
        name: 'Slightabrasion to extreme edge',
        checked: false,
        value: 96,
        image: 'assets/images/edgewearchipping/96.jpg',
      },
      {
        name: 'Perceptible Dings',
        checked: false,
        value: 94,
        image: 'assets/images/edgewearchipping/94.jpg',
      },
      {
        name: 'Rolled Overhang/Creases',
        checked: false,
        value: 85,
        image: 'assets/images/edgewearchipping/85.jpg',
      },
      {
        name: 'Slight Creasing/Breaks',
        checked: false,
        value: 75,
        image: 'assets/images/edgewearchipping/75.jpg',
      },
      {
        name: 'Single large chip/general breaks',
        checked: false,
        value: 55,
        image: 'assets/images/edgewearchipping/55.jpg',
      },
      {
        name: 'Heavily Worn Overflash',
        checked: false,
        value: 45,
        image: 'assets/images/edgewearchipping/45.jpg',
      },
      {
        name: 'Multiple Creases / Minor Tears',
        checked: false,
        value: 25,
        image: 'assets/images/edgewearchipping/25.jpg',
      },
      {
        name: 'Multiple Chips Out',
        checked: false,
        value: 10,
        image: 'assets/images/edgewearchipping/10.jpg',
      },
      {
        name: 'Brittle',
        checked: false,
        value: 5,
        image: 'assets/images/edgewearchipping/05.jpg',
      },
    ],
  },
  {
    _id: 13,
    name: 'Ink Density (Printing Defect)',
    defects: [
      {
        name: 'Deep, Dense Inks',
        checked: false,
        value: 100,
        image: 'assets/images/inkdensity/100.jpg',
      },
      {
        name: 'Areas of Fading',
        checked: false,
        value: 96,
        image: 'assets/images/inkdensity/96.jpg',
      },
      {
        name: 'Washed out / Visible Color Overlap',
        checked: false,
        value: 94,
        image: 'assets/images/inkdensity/94.jpg',
      },
    ],
  },
  {
    _id: 14,
    name: 'Interior Page Colour',
    defects: [
      {
        name: 'White',
        checked: false,
        value: 100,
        image: 'assets/images/interiorpagecolour/100.jpg',
      },
      {
        name: 'Off-White/White',
        checked: false,
        value: 98,
        image: 'assets/images/interiorpagecolour/98.jpg',
      },
      {
        name: 'Off-White',
        checked: false,
        value: 96,
        image: 'assets/images/interiorpagecolour/96.jpg',
      },
      {
        name: 'Cream/Off-White',
        checked: false,
        value: 94,
        image: 'assets/images/interiorpagecolour/94.jpg',
      },
      {
        name: 'Cream',
        checked: false,
        value: 92,
        image: 'assets/images/interiorpagecolour/92.jpg',
      },
      {
        name: 'Tan',
        checked: false,
        value: 30,
        image: 'assets/images/interiorpagecolour/30.jpg',
      },
      {
        name: 'Brown',
        checked: false,
        value: 20,
        image: 'assets/images/interiorpagecolour/20.jpg',
      },
    ],
  },
  {
    _id: 15,
    name: 'Interior Pages Missing',
    defects: [
      {
        name: 'All Pages Present',
        checked: false,
        value: 100,
        image: 'assets/images/interiorpagemissing/100.jpg',
      },
      {
        name: 'One or More (story) Pages Missing',
        checked: false,
        value: 5,
        image: 'assets/images/interiorpagemissing/05.jpg',
      },
    ],
  },
  {
    _id: 16,
    name: 'Lying Flat',
    defects: [
      {
        name: 'Totally Flat',
        checked: false,
        value: 100,
        image: 'assets/images/lyingflat/100.jpg',
      },
      {
        name: 'Slight Page Lifting',
        checked: false,
        value: 96,
        image: 'assets/images/lyingflat/96.jpg',
      },
      {
        name: 'Open Bend at Spine/warping',
        checked: false,
        value: 94,
        image: 'assets/images/lyingflat/94.jpg',
      },
      {
        name: 'Warping/Kinks at Spine',
        checked: false,
        value: 92,
        image: 'assets/images/lyingflat/92.jpg',
      },
      {
        name: 'Large Shallow Bend',
        checked: false,
        value: 75,
        image: 'assets/images/lyingflat/75.jpg',
      },
      {
        name: 'Excessive Warping/Lifting',
        checked: false,
        value: 70,
        image: 'assets/images/lyingflat/70.jpg',
      },
    ],
  },
  {
    _id: 17,
    name: 'Colour touch',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/paintcolourtouch/100.jpg',
      },
      {
        name: '< 5mm Coloured Areas',
        checked: false,
        value: 60,
        image: 'assets/images/paintcolourtouch/60.jpg',
      },
      {
        name: 'Obvious Amateur Colouring',
        checked: false,
        value: 40,
        image: 'assets/images/paintcolourtouch/40.jpg',
      },
      {
        name: 'Large Amounts of Paint',
        checked: false,
        value: 10,
        image: 'assets/images/paintcolourtouch/10.jpg',
      },
    ],
  },
  {
    _id: 18,
    name: 'Piece Out (wear/rip damage)',
    defects: [
      {
        name: 'Edges Complete',
        checked: false,
        value: 100,
        image: 'assets/images/pieceout/100.jpg',
      },
      {
        name: '1mm Flake Out',
        checked: false,
        value: 94,
        image: 'assets/images/pieceout/96.jpg',
      },
      {
        name: '< 3mm Piece Out',
        checked: false,
        value: 70,
        image: 'assets/images/pieceout/85.jpg',
      },
      {
        name: '3-5mm Piece Out',
        checked: false,
        value: 65,
        image: 'assets/images/pieceout/80.jpg',
      },
      {
        name: '5-10mm Piece Out',
        checked: false,
        value: 35,
        image: 'assets/images/pieceout/65.jpg',
      },
      {
        name: '5-20mm Piece Out',
        checked: false,
        value: 30,
        image: 'assets/images/pieceout/25.jpg',
      },
      {
        name: 'Large Piece Out',
        checked: false,
        value: 18,
        image: 'assets/images/pieceout/18.jpg',
      },
    ],
  },
  {
    _id: 19,
    name: 'Printer Creases',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/printerscreases/100.jpg',
      },
      {
        name: '50mm or less crease',
        checked: false,
        value: 92,
        image: 'assets/images/printerscreases/92.jpg',
      },
      {
        name: '50mm - 75mm crease',
        checked: false,
        value: 90,
        image: 'assets/images/printerscreases/90.jpg',
      },
      {
        name: 'Multiple 75mm creases',
        checked: false,
        value: 85,
        image: 'assets/images/printerscreases/85.jpg',
      },
      {
        name: 'Greater than 75mm crease(s)',
        checked: false,
        value: 80,
        image: 'assets/images/printerscreases/80.jpg',
      },
    ],
  },
  {
    _id: 20,
    name: 'Scratches',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/scratching/100.jpg',
      },
      {
        name: 'Just Perceptible Colour Break',
        checked: false,
        value: 96,
        image: 'assets/images/scratching/96.jpg',
      },
      {
        name: '3mm Scratch & flaking',
        checked: false,
        value: 94,
        image: 'assets/images/scratching/94.jpg',
      },
      {
        name: 'Deep 10mm Scratch',
        checked: false,
        value: 65,
        image: 'assets/images/scratching/65.jpg',
      },
      {
        name: 'Large Superficial Scratches',
        checked: false,
        value: 50,
        image: 'assets/images/scratching/50.jpg',
      },
      {
        name: 'Page-Thickness Scratches',
        checked: false,
        value: 40,
        image: 'assets/images/scratching/40.jpg',
      },
      {
        name: 'Large Noticeable Scratch',
        checked: false,
        value: 30,
        image: 'assets/images/scratching/30.jpg',
      },
    ],
  },
  {
    _id: 21,
    name: 'Soiling',
    defects: [
      {
        name: 'Totally Clean',
        checked: false,
        value: 100,
        image: 'assets/images/coverwhiteness/100.jpg',
      },
      {
        name: 'Tiny Fingerprint < 5mm',
        checked: false,
        value: 90,
        image: 'assets/images/soiling/90.jpg',
      },
      {
        name: 'Soiling Tracks',
        checked: false,
        value: 85,
        image: 'assets/images/soiling/85.jpg',
      },
      {
        name: 'General light Soiling',
        checked: false,
        value: 80,
        image: 'assets/images/soiling/80.jpg',
      },
      {
        name: 'Moderate Contact Soiling/Dirt',
        checked: false,
        value: 60,
        image: 'assets/images/soiling/60.jpg',
      },
    ],
  },
  {
    _id: 22,
    name: 'Spine creases',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/spinecreases/100.jpg',
      },
      {
        name: 'Single Perceptible Crease',
        checked: false,
        value: 98,
        image: 'assets/images/spinecreases/98.jpg',
      },
      {
        name: '4mm Colour Breaking Crease',
        checked: false,
        value: 94,
        image: 'assets/images/spinecreases/94.jpg',
      },
      {
        name: 'Several Colour Breaking Creases',
        checked: false,
        value: 85,
        image: 'assets/images/spinecreases/85.jpg',
      },
      {
        name: 'Uniform Creasing < 7mm',
        checked: false,
        value: 80,
        image: 'assets/images/spinecreases/80.jpg',
      },
      {
        name: 'Multiple Deep Creases',
        checked: false,
        value: 45,
        image: 'assets/images/spinecreases/45.jpg',
      },
      {
        name: 'Heavy Creasing',
        checked: false,
        value: 35,
        image: 'assets/images/spinecreases/35.jpg',
      },
    ],
  },
  {
    _id: 23,
    name: 'Spine Roll',
    defects: [
      {
        name: 'Tight, Flat Spine',
        checked: false,
        value: 100,
        image: 'assets/images/spineroll/100.jpg',
      },
      {
        name: 'Slight Spine Roll',
        checked: false,
        value: 60,
        image: 'assets/images/spineroll/60.jpg',
      },
      {
        name: 'Substantial Spine Roll',
        checked: false,
        value: 30,
        image: 'assets/images/spineroll/30.jpg',
      },
      {
        name: 'Severe Spine Roll',
        checked: false,
        value: 15,
        image: 'assets/images/spineroll/15.jpg',
      },
    ],
  },
  {
    _id: 24,
    name: 'Spine Stress Marks',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/spinestress/100.jpg',
      },
      {
        name: 'Just Perceptible (<3mm)',
        checked: false,
        value: 96,
        image: 'assets/images/spinestress/96.jpg',
      },
      {
        name: '2-4mm Non Colour Breaking',
        checked: false,
        value: 94,
        image: 'assets/images/spinestress/94.jpg',
      },
      {
        name: 'Multiple non colour-breaking Creases',
        checked: false,
        value: 70,
        image: 'assets/images/spinestress/70.jpg',
      },
    ],
  },
  {
    _id: 25,
    name: 'Spine tears',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/spinetears/100.jpg',
      },
      {
        name: '<5mm Tear',
        checked: false,
        value: 94,
        image: 'assets/images/spinetears/94.jpg',
      },
      {
        name: '10mm Tear',
        checked: false,
        value: 50,
        image: 'assets/images/spinetears/50.jpg',
      },
      {
        name: '20mm Tear or Several Smaller',
        checked: false,
        value: 45,
        image: 'assets/images/spinetears/45.jpg',
      },
      {
        name: 'Very Large Tear',
        checked: false,
        value: 20,
        image: 'assets/images/spinetears/20.jpg',
      },
      {
        name: 'Book-Length Split',
        checked: false,
        value: 5,
        image: 'assets/images/spinetears/5.jpg',
      },
    ],
  },
  {
    _id: 26,
    name: 'Staining',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/staining/100.jpg',
      },
      {
        name: 'Just Perceptible Mark',
        checked: false,
        value: 90,
        image: 'assets/images/staining/90.jpg',
      },
      {
        name: 'Moderate fingerprint stain',
        checked: false,
        value: 65,
        image: 'assets/images/staining/65.jpg',
      },
      {
        name: 'Label Adhesive',
        checked: false,
        value: 50,
        image: 'assets/images/staining/50.jpg',
      },
      {
        name: 'Single large Stain',
        checked: false,
        value: 45,
        image: 'assets/images/staining/45.jpg',
      },
      {
        name: 'Large rust/oxidation stain',
        checked: false,
        value: 35,
        image: 'assets/images/staining/35.jpg',
      },
      {
        name: 'Water Damage',
        checked: false,
        value: 18,
        image: 'assets/images/staining/18.jpg',
      },
    ],
  },
  {
    _id: 27,
    name: 'Stamps',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/stamps/100.jpg',
      },
      {
        name: 'Small Date Stamp',
        checked: false,
        value: 94,
        image: 'assets/images/coverwhiteness/90.jpg',
      },
      {
        name: 'Cover Stamp < 20mm',
        checked: false,
        value: 92,
        image: 'assets/images/stamps/94.jpg',
      },
      {
        name: 'Bookshop Stamp',
        checked: false,
        value: 90,
        image: 'assets/images/stamps/92.jpg',
      },
      {
        name: 'Multiple Large Stamps',
        checked: false,
        value: 80,
        image: 'assets/images/stamps/80.jpg',
      },
    ],
  },
  {
    _id: 28,
    name: 'Staple placement',
    defects: [
      {
        name: 'Perfect Placement',
        checked: false,
        value: 100,
        image: 'assets/images/staplewear/100.jpg',
      },
      {
        name: 'Slightly Off Alignment',
        checked: false,
        value: 98,
        image: 'assets/images/stapleplacement/98.jpg',
      },
      {
        name: '1-3mm off-staple',
        checked: false,
        value: 96,
        image: 'assets/images/stapleplacement/96.jpg',
      },
      {
        name: '>3mm mis-staple',
        checked: false,
        value: 80,
        image: 'assets/images/stapleplacement/80.jpg',
      },
      {
        name: 'Amateur Re-Staple',
        checked: false,
        value: 20,
        image: 'assets/images/stapleplacement/20.jpg',
      },
    ],
  },
  {
    _id: 29,
    name: 'Staple Rust',
    defects: [
      {
        name: 'Clean, Shiny Staple',
        checked: false,
        value: 100,
        image: 'assets/images/staplewear/100.jpg',
      },
      {
        name: 'Matt Appearance',
        checked: false,
        value: 94,
        image: 'assets/images/staplerust/94.jpg',
      },
      {
        name: 'Moderate Tarnish/Rust Signs',
        checked: false,
        value: 92,
        image: 'assets/images/staplerust/92.jpg',
      },
      {
        name: 'Advanced Rust with Migration',
        checked: false,
        value: 30,
        image: 'assets/images/staplerust/30.jpg',
      },
      {
        name: 'Substantial Migration',
        checked: false,
        value: 15,
        image: 'assets/images/staplerust/15.jpg',
      },
    ],
  },
  {
    _id: 30,
    name: 'Staple wear',
    defects: [
      {
        name: 'Perfect; As-new',
        checked: false,
        value: 100,
        image: 'assets/images/staplewear/100.jpg',
      },
      {
        name: 'Perceptible Staple Wear',
        checked: false,
        value: 96,
        image: 'assets/images/staplewear/96.jpg',
      },
      {
        name: 'Buckled Spine; colour breaking creases',
        checked: false,
        value: 85,
        image: 'assets/images/staplewear/85.jpg',
      },
      {
        name: 'Large Creases and/or small tears',
        checked: false,
        value: 55,
        image: 'assets/images/staplewear/55.jpg',
      },
      {
        name: 'Considerable Staple Wear',
        checked: false,
        value: 50,
        image: 'assets/images/staplewear/50.jpg',
      },
      {
        name: 'Severe Staple Wear',
        checked: false,
        value: 30,
        image: 'assets/images/staplewear/30.jpg',
      },
      {
        name: 'Cover Detached',
        checked: false,
        value: 10,
        image: 'assets/images/staplewear/10.jpg',
      },
    ],
  },
  {
    _id: 31,
    name: 'Subscription crease',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/subcrease/100.jpg',
      },
      {
        name: 'Noticeable Crease',
        checked: false,
        value: 55,
        image: 'assets/images/subcrease/55.jpg',
      },
      {
        name: 'Obvious Folding Damage',
        checked: false,
        value: 40,
        image: 'assets/images/subcrease/40.jpg',
      },
    ],
  },
  {
    _id: 32,
    name: 'Sun Shadow',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/perfect_in_every_way.jpg',
      },
      {
        name: 'Just Perceptible',
        checked: false,
        value: 99,
        image: 'assets/images/sunshadow/99.jpg',
      },
      {
        name: 'Slight Tanning',
        checked: false,
        value: 98,
        image: 'assets/images/sunshadow/98.jpg',
      },
      {
        name: 'Unobtrusive Sun Shadow',
        checked: false,
        value: 96,
        image: 'assets/images/sunshadow/96.jpg',
      },
      {
        name: 'Noticeable Sun Shadow',
        checked: false,
        value: 85,
        image: 'assets/images/sunshadow/85.jpg',
      },
      {
        name: 'Obvious Sun Shadow',
        checked: false,
        value: 80,
        image: 'assets/images/sunshadow/80.jpg',
      },
    ],
  },
  {
    _id: 33,
    name: 'Tape',
    defects: [
      {
        name: 'No Tape',
        checked: false,
        value: 100,
        image: 'assets/images/tape/100.jpg',
      },
      {
        name: 'Amateur Tear Seal <10mm',
        checked: false,
        value: 55,
        image: 'assets/images/tape/55.jpg',
      },
      {
        name: 'Small Amateur Repair',
        checked: false,
        value: 35,
        image: 'assets/images/tape/35.jpg',
      },
      {
        name: 'Large Repair (Complete Spine)',
        checked: false,
        value: 20,
        image: 'assets/images/tape/20.jpg',
      },
    ],
  },
  {
    _id: 34,
    name: 'Tears',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/perfect_in_every_way.jpg',
      },
      {
        name: 'Single tear <5mm',
        checked: false,
        value: 90,
        image: 'assets/images/spinetears/94.jpg',
      },
      {
        name: 'Multiple <3mm tears',
        checked: false,
        value: 80,
        image: 'assets/images/tears/80.jpg',
      },
      {
        name: 'Several 3-5mm Tears',
        checked: false,
        value: 55,
        image: 'assets/images/tears/55.jpg',
      },
      {
        name: '5-10mm Tear',
        checked: false,
        value: 50,
        image: 'assets/images/tears/50.jpg',
      },
      {
        name: '10-20mm Tear',
        checked: false,
        value: 40,
        image: 'assets/images/tears/40.jpg',
      },
      {
        name: '20-30 mm Tear',
        checked: false,
        value: 35,
        image: 'assets/images/tears/35.jpg',
      },
      {
        name: 'Large Tear',
        checked: false,
        value: 25,
        image: 'assets/images/tears/25.jpg',
      },
    ],
  },
  {
    _id: 35,
    name: 'Warping',
    defects: [
      {
        name: 'None',
        checked: false,
        value: 100,
        image: 'assets/images/lyingflat/100.jpg',
      },
      {
        name: 'Just Noticable',
        checked: false,
        value: 94,
        image: 'assets/images/warping/94.jpg',
      },
      {
        name: 'Bumpy',
        checked: false,
        value: 55,
        image: 'assets/images/warping/55.jpg',
      },
      {
        name: 'Noticeable Warping',
        checked: false,
        value: 40,
        image: 'assets/images/warping/40.jpg',
      },
      {
        name: 'Water Damage',
        checked: false,
        value: 30,
        image: 'assets/images/warping/30.jpg',
      },
      {
        name: 'Heavy Wrinkling',
        checked: false,
        value: 25,
        image: 'assets/images/warping/25.jpg',
      },
    ],
  },
  {
    _id: 36,
    name: 'Writing',
    defects: [
      {
        name: 'No Writing',
        checked: false,
        value: 100,
        image: 'assets/images/perfect_in_every_way.jpg',
      },
      {
        name: 'Unobtrusive writing; pencil BC',
        checked: false,
        value: 96,
        image: 'assets/images/writing/96.jpg',
      },
      {
        name: 'Single Date Mark (Ballpoint)',
        checked: false,
        value: 92,
        image: 'assets/images/writing/92.jpg',
      },
      {
        name: 'Multiple Ballpoint on Cover',
        checked: false,
        value: 65,
        image: 'assets/images/writing/65.jpg',
      },
      {
        name: 'Large Written Characters',
        checked: false,
        value: 55,
        image: 'assets/images/writing/55.jpg',
      },
      {
        name: 'Marker Pen',
        checked: false,
        value: 30,
        image: 'assets/images/writing/30.jpg',
      },
      {
        name: 'Scrawl',
        checked: false,
        value: 20,
        image: 'assets/images/writing/20.jpg',
      },
    ],
  },
];
